#!/usr/bin/env bash
TARGET_FILE=$1
if [ -z "$TARGET_FILE" ]; then
  echo "Usage: $0 <target-file>"
  exit 1
fi

ARTIFACT_ID_BLACKLIST=(\
operaton-webapp \
openapi-java-client \
operaton-bpm-assert-qa \
operaton-wildfly26-subsystem \
operaton-wildfly-subsystem \
operaton-bpm-run-core \
operaton-bpm-run-qa-integration-tests \
qa-plugins-spin-dataformat-all \
large-data-tests \
operaton-qa-db-test-old-engine \
operaton-qa-integration-tests-engine-jakarta  \
operaton-qa-upgrade-test-migration \
operaton-qa-integration-tests-engine \
operaton-example-invoice \
operaton-bpm-quarkus-engine-qa \
operaton-webapp \
)

VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout | tail -n 1)

cat <<EOF > $TARGET_FILE
<!-- This file is generated by jacoco-create-report-pom.sh script -->
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.operaton.bpm</groupId>
  <artifactId>jacoco-aggregate-report</artifactId>
  <version>${VERSION}</version>
  <dependencies>
EOF

find . -type d | while read -r dir; do
  if [[ -d "$dir/src/test/java" || -d "$dir/target/generated-test-sources/java" ]]; then
    echo "Processing $dir"

    GROUP_ID=$(xq -e /project/groupId $dir/pom.xml)
    if [ -z "$GROUP_ID" ]; then
      GROUP_ID=$(xq -e /project/parent/groupId $dir/pom.xml)
    fi
    ARTIFACT_ID=$(xq -e /project/artifactId $dir/pom.xml)

    if [[ ! " ${ARTIFACT_ID_BLACKLIST[@]} " =~ " ${ARTIFACT_ID} " ]]; then
      cat <<EOF >> $TARGET_FILE
        <dependency>
        <groupId>${GROUP_ID}</groupId>
        <artifactId>${ARTIFACT_ID}</artifactId>
        <version>\${project.version}</version>
      </dependency>
EOF
    fi
  fi
done

cat <<EOF >> $TARGET_FILE
  </dependencies>
  <build>
    <defaultGoal>verify</defaultGoal>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.8</version>
        <executions>
          <execution>
            <id>report-aggregate</id>
            <phase>verify</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
              <configuration>
                <dataFileIncludes>
                    <dataFileInclude>**/jacoco.exec</dataFileInclude>
                </dataFileIncludes>
                <outputDirectory>\${project.reporting.outputDirectory}/jacoco-aggregate</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.4.2</version>
        <configuration>
          <skipIfEmpty>true</skipIfEmpty>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
EOF

