/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. Camunda licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.operaton.bpm.engine.test.api.authorization;

import java.util.Date;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;

import org.operaton.bpm.engine.AuthorizationException;
import org.operaton.bpm.engine.TaskService;
import org.operaton.bpm.engine.task.Task;
import org.operaton.bpm.engine.test.junit5.ParameterizedTestExtension.Parameter;
import org.operaton.bpm.engine.test.junit5.ParameterizedTestExtension.Parameterized;
import org.operaton.bpm.engine.test.junit5.ParameterizedTestExtension.Parameters;
import org.operaton.bpm.engine.test.util.ClockTestUtil;
import org.operaton.bpm.engine.test.util.ObjectProperty;
import org.operaton.bpm.engine.test.util.TriConsumer;

import static org.operaton.bpm.engine.authorization.Authorization.ANY;
import static org.operaton.bpm.engine.authorization.Permissions.TASK_ASSIGN;
import static org.operaton.bpm.engine.authorization.Permissions.UPDATE;
import static org.operaton.bpm.engine.authorization.Permissions.UPDATE_TASK;
import static org.operaton.bpm.engine.authorization.Resources.PROCESS_DEFINITION;
import static org.operaton.bpm.engine.authorization.Resources.TASK;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.fail;

@Parameterized
public class SetTaskPropertyAuthorizationTest extends AuthorizationTest {

  protected static final String PROCESS_KEY = "oneTaskProcess";

  @Parameter(0)
  public String operationName;
  @Parameter(1)
  public TriConsumer<TaskService, String, Object> operation;
  @Parameter(2)
  public String taskId;
  @Parameter(3)
  public Object value;

  protected boolean deleteTask;

  /**
   * Parameters:
   * <p>
   * simpleMethodName: Used for readability (printing first argument as test method instead of a autogenerated consumer name)
   * methodToCall: The method to call during test cases
   * setValue: The value to use to set property to
   * taskQueryBuilderMethodName: The corresponding taskQuery builder method name to use for assertion purposes
   */
  @Parameters
  public static List<Object[]> data() {
    TriConsumer<TaskService, String, Object> setPriority = (taskService, taskId, value) -> taskService.setPriority(taskId, (int) value);
    TriConsumer<TaskService, String, Object> setName = (taskService, taskId, value) -> taskService.setName(taskId, (String) value);
    TriConsumer<TaskService, String, Object> setDescription = (taskService, taskId, value) -> taskService.setDescription(taskId, (String) value);
    TriConsumer<TaskService, String, Object> setDueDate = (taskService, taskId, value) -> taskService.setDueDate(taskId, (Date) value);
    TriConsumer<TaskService, String, Object> setFollowUpDate = (taskService, taskId, value) -> taskService.setFollowUpDate(taskId, (Date) value);

    return List.of(new Object[][] {
        {"setPriority", setPriority, "taskId", 80 },
        {"setName", setName, "taskId", "name" },
        {"setDescription", setDescription, "taskId", "description" },
        {"setDueDate", setDueDate, "taskId",  ClockTestUtil.setClockToDateWithoutMilliseconds() },
        {"setFollowUpDate", setFollowUpDate, "taskId", ClockTestUtil.setClockToDateWithoutMilliseconds() }
    });
  }

  @Override
  @BeforeEach
  public void setUp() {
    testRule.deploy("org/operaton/bpm/engine/test/api/oneTaskProcess.bpmn20.xml");
    super.setUp();
  }

  @TestTemplate
  void shouldSetOperationStandaloneWithoutAuthorization() {
    // given
    createTask(taskId);
    assertThatThrownBy(() -> operation.accept(taskService, taskId, value), "It should not be possible to " + operationName)
        .isInstanceOf(AuthorizationException.class)
        .hasMessageContaining("The user with id '%s' does not have one of the following permissions: 'TASK_ASSIGN'".formatted(userId));
    deleteTask(taskId, true);
  }

  @TestTemplate
  void shouldSetOperationStandalone() {
    // given
    createTask(taskId);
    createGrantAuthorization(TASK, taskId, userId, UPDATE);

    // when
    operation.accept(taskService, taskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);

    deleteTask(taskId, true);
  }

  @TestTemplate
  void shouldSetOperationStandaloneWithTaskAssignPermission() {
    // given
    createTask(taskId);
    createGrantAuthorization(TASK, taskId, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, taskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);

    deleteTask(taskId, true);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithTaskAssignPermissionOnTask() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, startedTaskId, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithoutAuthorization() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    // when + then
    assertThatThrownBy(() -> operation.accept(taskService, startedTaskId, value),
            "It should not be possible to " + operationName)
        .isInstanceOf(AuthorizationException.class)
        .hasMessageContaining(userId)
        .hasMessageContaining(UPDATE.getName())
        .hasMessageContaining(startedTaskId)
        .hasMessageContaining(TASK.resourceName())
        .hasMessageContaining(UPDATE_TASK.getName())
        .hasMessageContaining(PROCESS_DEFINITION.resourceName());
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithUpdatePermissionOnAnyTask() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, ANY, userId, UPDATE);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithTaskAssignPermissionOnAnyTask() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, ANY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithUpdateTasksPermissionOnProcessDefinition() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, UPDATE_TASK);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithTaskAssignPermissionOnProcessDefinition() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessTask() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, startedTaskId, userId, UPDATE);
    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, UPDATE_TASK);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  @TestTemplate
  void shouldSetOperationOnProcessWithTaskAssignPermission() {
    // given
    startProcessInstanceByKey(PROCESS_KEY);
    String startedTaskId = selectSingleTask().getId();

    createGrantAuthorization(TASK, startedTaskId, userId, TASK_ASSIGN);
    createGrantAuthorization(PROCESS_DEFINITION, PROCESS_KEY, userId, TASK_ASSIGN);

    // when
    operation.accept(taskService, startedTaskId, value);

    // then
    Task task = selectSingleTask();

    assertThat(task).isNotNull();
    assertHasPropertyValue(task, operationName, value);
  }

  private void assertHasPropertyValue(Task task, String operationName, Object expectedValue) {
    try {
      Object actualValue = ObjectProperty.ofSetterMethod(task, operationName).getValue();

      assertThat(actualValue).isEqualTo(expectedValue);
    } catch (Exception e) {
      fail("Failed to assert property for operationName=%s due to : %s".formatted(operationName, e.getMessage()));
    }
  }
}
