name: Linting

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-slim
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint ADR files
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        continue-on-error: true
        with:
          globs: |
            docs/decisions/**/*.md
          config: '.github/markdownlint-cli2.yml'

