name: Maintenance

on:
  workflow_dispatch:
    inputs:
      slack_url:
        description: 'Update Slack Invitation URL'
        type: string

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  update-slack-invitation-url:
    if: ${{ github.event.inputs.slack_url}}
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Update Slack Invitation URL
        run: |
          .devenv/scripts/maintenance/update-slack-link.sh ${{ github.event.inputs.slack_url}}
        shell: bash
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore: Update Slack Invitation URL"