name: Post Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag of the release'
        required: true
        default: 'early-access'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ github.event.release.tag_name || steps.version.outputs.version }}
      snapshot: ${{ github.event.release.tag_name == 'early-access' || github.event.inputs.tag_name == 'early-access' }}
    steps:
      - name: Checkout Code
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version
        id: version
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          RELEASE_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout | tail -n 1 | sed -e 's/-SNAPSHOT//')
          echo "version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

  docker:
    name: Notify Docker Repository for Image Creation
    runs-on: ubuntu-24.04
    needs:
      - prepare
    steps:
      - name: Notify Docker Repository
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.DOCKER_ACTION_DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"ref":"main","inputs":{"version": "${{ needs.prepare.outputs.version}}","snapshot": "${{needs.prepare.outputs.snapshot }}"}}' \
            https://api.github.com/repos/operaton/operaton-docker/actions/workflows/build-test-and-publish.yml/dispatches)
          if [ "$response" -ne 204 ]; then
            echo "Failed to notify Docker repository. HTTP response code: $response"
            exit 1
          fi
