name: Check GitHub Workflow Security

permissions:
  contents: read

on:
  push:
    branches: ["main", "release/**"]
    paths:
      - .github/workflows/*.yml
      - .github/actions/*.yml
      - .github/dependabot.yml
  pull_request:
    paths:
      - .github/workflows/*.yml
      - .github/actions/*.yml
      - .github/dependabot.yml

jobs:
  zizmor:
    name: Analyze workflow security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          persona: regular # More critical: pedantic, auditor
          advanced-security: false # We don't have this enabled atm
          config: .github/zizmor/config.yml
